name = "cosmikdev"
main = "worker/index.js"
compatibility_date = "2026-09-13"
workers_dev = true

routes = [
  { pattern = "cosmik.dev", custom_domain = true },
  { pattern = "www.cosmik.dev", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "COSMIK_KV"
id = "696129bec3a449b4be2b737dd8364f4f"

[[durable_objects.bindings]]
name = "TWITCH_SOCKET"
class_name = "TwitchChatSocket"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TwitchChatSocket"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ChatRoom"]

[triggers]
crons = ["*/5 * * * *"]
